language: node_js
node_js:
- 7
before_install:
- openssl aes-256-cbc -K $encrypted_d6c7aa5064d7_key -iv $encrypted_d6c7aa5064d7_iv
  -in tools/deploy/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
before_script:
- mv -fv tools/deploy/ssh_config ~/.ssh/config
- cat /home/travis/.ssh/config
- git checkout -qf $TRAVIS_BRANCH
script:

- git remote add deploy root@sunbeam:/usr/local/codelib/sunbeam-front.git
- if [ $TRAVIS_BRANCH = master ]; then git push deploy $TRAVIS_BRANCH; fi

git:
  depth: false
cache:
  directories:
  - node_modules
